<?php

namespace Tests\Unit;

use App\Traits\Helper;
use PHPUnit\Framework\TestCase;

class ValidatePhoneNumbersTest extends TestCase
{

    private $helperTrait;
    public function setUp(): void
    {
        $this->helperTrait = $this->getObjectForTrait(Helper::class);
       parent::setUp(); // TODO: Change the autogenerated stub
    }


    function test_can_validate_correct_phone_pattern()
    {
        $pattern = '\(251\)?[1-59]\d{8}$';
        $validPhoneNumber = '(251)966002259';
        $is_valid = $this->helperTrait->checkPhoneNumberValidation($pattern,$validPhoneNumber);
        $this->assertEquals($is_valid,1);

    }

    function test_can_validate_wrong_phone_pattern()
    {
        $pattern = '\(251\)?[1-59]\d{8}$';
        $wrongPhoneNumber = '(251)9119454961';
        $is_valid = $this->helperTrait->checkPhoneNumberValidation($pattern,$wrongPhoneNumber);
        $this->assertEquals($is_valid,0);

    }

    function test_can_generate_code_form_valid_phone_number()
    {
        $validPhoneNumber = '(251)966002259';
        $code = $this->helperTrait->generateCodeFromPhoneNumber($validPhoneNumber);
        $this->assertEquals($code,'251');

    }
}
